"""create evaluations table

Revision ID: 33548f304586
Revises: d78ccd97acee
Create Date: 2026-07-11 12:35:38.318426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33548f304586'
down_revision: Union[str, Sequence[str], None] = 'd78ccd97acee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('run_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('actual_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('answer_score', sa.Float(), nullable=True),
    sa.Column('citation_score', sa.Float(), nullable=True),
    sa.Column('guardrail_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_document_id'), 'evaluations', ['document_id'], unique=False)
    op.create_index(op.f('ix_evaluations_organization_id'), 'evaluations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_organization_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_document_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
