"""create human reviews table

Revision ID: 382f67205561
Revises: 33548f304586
Create Date: 2026-07-11 13:23:37.115321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '382f67205561'
down_revision: Union[str, Sequence[str], None] = '33548f304586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('original_answer', sa.Text(), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guardrail_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_assistant_message_id'), 'human_reviews', ['assistant_message_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_created_at'), 'human_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_reviews_document_id'), 'human_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_organization_id'), 'human_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_reviewer_id'), 'human_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_session_id'), 'human_reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_status'), 'human_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_human_reviews_workflow_run_id'), 'human_reviews', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_workflow_run_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_status'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_session_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_reviewer_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_organization_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_document_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_created_at'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_assistant_message_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    # ### end Alembic commands ###
